"""

Django settings for curio project.



Generated by 'django-admin startproject' using Django 5.0.6.



For more information on this file, see

https://docs.djangoproject.com/en/5.0/topics/settings/



For the full list of settings and their values, see

https://docs.djangoproject.com/en/5.0/ref/settings/

"""




from pathlib import Path

import os



# Build paths inside the project like this: BASE_DIR / 'subdir'.

BASE_DIR = Path(__file__).resolve().parent.parent



# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'default-secret-key')



# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = False



ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', 'curio.vercel.app,localhost').split(',')



# Application definition

INSTALLED_APPS = [

    'django.contrib.admin',

    'django.contrib.auth',

    'django.contrib.contenttypes',

    'django.contrib.sessions',

    'django.contrib.messages',

    'django.contrib.staticfiles',

    'blog.apps.BlogConfig',

    'widget_tweaks',

    'rest_framework',

]



MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'csp.middleware.CSPMiddleware',

]



ROOT_URLCONF = 'curio.urls'



TEMPLATES = [

    {

        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [

            BASE_DIR / "templates/",

        ],

        'APP_DIRS': True,

        'OPTIONS': {

            'context_processors': [

                'django.template.context_processors.debug',

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',

            ],

        },

    },

]



WSGI_APPLICATION = 'curio.wsgi.application'



# Database configuration

DATABASES = {

    'default': {

        'ENGINE': 'django.db.backends.postgresql',

        'NAME': os.getenv('DB_NAME'),

        'USER': os.getenv('DB_USER'),

        'PASSWORD': os.getenv('DB_PASSWORD'),

        'HOST': os.getenv('DB_HOST'),

        'PORT': os.getenv('DB_PORT', '5432'),

    }

}



# Password validation

AUTH_PASSWORD_VALIDATORS = [

    {

        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',

    },

]



# Internationalization

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)

STATIC_URL = '/static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'



MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'



# Security settings

SECURE_SSL_REDIRECT = True

SECURE_HSTS_SECONDS = 31536000  # 1 year

SECURE_HSTS_INCLUDE_SUBDOMAINS = True

SECURE_HSTS_PRELOAD = True

SECURE_BROWSER_XSS_FILTER = True

SECURE_CONTENT_TYPE_NOSNIFF = True



CSRF_COOKIE_SECURE = True

CSRF_COOKIE_HTTPONLY = True



SESSION_COOKIE_SECURE = True

SESSION_COOKIE_HTTPONLY = True



# Logging configuration

LOGGING = {

    'version': 1,

    'disable_existing_loggers': False,

    'handlers': {

        'file': {

            'level': 'ERROR',

            'class': 'logging.FileHandler',

            'filename': BASE_DIR / 'django_errors.log',

        },

    },

    'loggers': {

        'django': {

            'handlers': ['file'],

            'level': 'ERROR',

            'propagate': True,

        },

    },

}



# Custom user model

AUTH_USER_MODEL = 'blog.CustomUser'



# Login URL

LOGIN_URL = '/login/'



DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
