# Generated by Django 5.1.3 on 2024-12-04 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='love_reactions',
            field=models.ManyToManyField(blank=True, related_name='loved_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
