# quotes.py

quotes = [
    "The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt",
    "The purpose of our lives is to be happy. – Dalai Lama",
    "Life is what happens when you're busy making other plans. – John Lennon",
    "Get busy living or get busy dying. – Stephen King",
    "You only live once, but if you do it right, once is enough. – Mae West",
    "The shadow that once was my enemy is now my strength. – Shadow Slave",
    "Pain is just a moment. The determination to rise above it lasts forever. – Shadow Slave",
    "Only when you embrace darkness can you see the true light. – Shadow Slave",
    "In this world, power is not given; it is seized. – Shadow Slave",
    "Every victory has its cost, but the greatest ones are those that make you who you are. – Shadow Slave",
    "You can't change the past, but you can shape the future with the choices you make now. – Shadow Slave",
    "The true measure of strength isn't in what you can do for yourself, but what you can endure for others. – Shadow Slave",
    "Fear is a chain. Break it, and you will be unstoppable. – Shadow Slave",
    "Trust in your path, even if you are the only one who believes in it. – Shadow Slave",
    "Life is like a shadow—it’s not what it appears to be, but the part you choose to chase. – Shadow Slave",
    "To fight the darkness, you must first understand it. Only then can you overcome it. – Shadow Slave",
    "Your greatest enemy is the doubt that lives inside you. – Shadow Slave",
    "No victory is complete without the scars that remind you of what you’ve overcome. – Shadow Slave",
    "Every scar tells a story, and mine will be one of conquest. – Shadow Slave",
    "Even when you feel lost in the darkness, remember that the first step to finding the light is to keep moving. – Shadow Slave",
    "Power doesn’t come from fear; it comes from defying it. – Shadow Slave",
    "True strength is forged in the flames of hardship, not in the comfort of ease. – Shadow Slave",
    "Those who walk alone may stumble, but they are the ones who truly find their way. – Shadow Slave",
    "We are all shadows, but the way we cast our light defines who we are. – Shadow Slave",
    "A hero is not defined by what they have, but by what they give and sacrifice. – Shadow Slave",
    "Embrace failure, for it is the silent teacher that prepares you for greatness. – Shadow Slave",
    "The path of power is filled with challenges, but that’s where the real tests begin. – Shadow Slave",
    "Victory is not just a goal; it's the byproduct of relentless will. – Shadow Slave",
    "A heart forged in shadow is the one that knows both the weight of loss and the value of triumph. – Shadow Slave",
    "I am the storm, and the storm is me. – Shadow Slave",
    "You can either let fear control you or let it fuel you. The choice defines your destiny. – Shadow Slave",
    "Those who live in the light cannot comprehend the strength required to thrive in the dark. – Shadow Slave",
    "Never underestimate the power of a silent resolve. – Shadow Slave",
    "In the end, we are all defined by the battles we choose to fight and the ones we choose to face alone. – Shadow Slave",
    "To conquer the world, you first must conquer yourself. – Shadow Slave",
    "A shadow's true power is not in hiding from the light, but in becoming it. – Shadow Slave",
    "A real warrior does not fear the unknown; they become the unknown. – Shadow Slave",
    "The strongest chains are the ones you don’t see until it’s too late. – Shadow Slave",
    "Every defeat is simply the foundation for the next victory. – Shadow Slave",
    "You don't need to be the strongest to win. You just need to be willing to fight when others won’t. – Shadow Slave"
]

